### ISSUE TITLE
Can't make a subclass of QWidget plugin

### ISSUE THREAD

**Issue by enjoysmath** [Rockhopper-Technologies/pluginlib#1]
builtins.TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

from PyQt5.QtWidgets import QWidget
import pluginlib

@pluginlib.Parent('bancats plugin widget')
class PluginWidget(QWidget):
   @pluginlib.abstractmethod
   def __init__(self, plugin=None, new=None):
      super().__init__()
      if new is None:
         new = True
         
      if new:
         assert(plugin is not None)
         self._plugin = plugin
         PluginWidget.setup(self)
   
   @pluginlib.abstractmethod
   def __setstate__(self, data):
      self.__init__(new=False)
      self._plugin = data['ext']
      PluginWidget.setup(self)
      
   @pluginlib.abstractmethod  
   def __getstate__(self):
      data = {
         'plugin' : self._plugin
      }
      return data
   
   @pluginlib.abstractmethod
   def setup(self):
      pass
   
   @property
   def plugin(self):
      return self._plugin
```

**Comment by avylove** [comment]
This is because QWidget is using metaclasses too, but the class you are deriving from isn't a subclass of those metaclasses. We might still be able to support this, but it will take some time to determine the best way to resolve the conflicts. In the meantime, you might be able to create a QWidget instance as an instance variable and use `__getattr__` to reference it. If this works for your use case, it would probably be a cleaner solution. Something similar to this.

```
from PyQt5.QtWidgets import QWidget
import pluginlib

@pluginlib.Parent('widget')
class PluginWidget(object):

    def __init__(self):
        self._widget = QWidget()

    def __getattr__(self, attr):
        return getattr(self._widget, attr)
```

**Comment by enjoysmath** [comment]
I will just get around this by having having the plugin be a object as in
the examples, and then return a widget from one of its methods.

By the way, does your library support pyinstaller (python-to-EXE)
conversion?  Or will something break if I have an otherwise working EXE and
try to let the user load in their own python modules as plugins?

**Comment by avylove** [comment]
I did some research and it might be supportable, but it would be complicated to implement and could have unexpected side effects, so I'm not going to pursue it. I added an entry documenting the behavior and the workaround suggested to the [FAQ](https://pluginlib.readthedocs.io/en/stable/faq.html#why-am-i-getting-typeerror-metaclass-conflict) in the latest [release](https://github.com/Rockhopper-Technologies/pluginlib/releases/tag/0.7.0).
