### ISSUE TITLE
Can't import plugins

### ISSUE THREAD

**Issue by enjoysmath** [Rockhopper-Technologies/pluginlib#2]
I've followed the directions perfectly for constructing the classes.  

However, when doing:

```
   def load_plugins(self):
      import pluginlib
      import core.plugin
      self._pluginLoader = pluginlib.PluginLoader(paths=['plugin'])
      self.test_plugin()
```

I have my plugin called "terminal_object.py" (class=TerminalObject)  within the plugin directory which resides in the main directory of my running application.  It loads the base class fine, but it's dictionary is empty.

What am I forgetting to do?

Thanks.

**Comment by avylove** [comment]
It's hard to tell from your code everything that's happening, but essentially you should have something like this:

```python
# core/plugin.py
import pluginlib

@pluginlib.Parent('widget')
class PluginWidget(object):
    pass
```

```python
# plugins/terminal_object.py
import core.plugin

class TerminalObject(core.plugin.PluginWidget):
    _alias_ = 'terminal'
```

```python
# core/main.py
import pluginlib
import core.plugin

def load_plugins():
    loader = pluginlib.PluginLoader(paths=['plugins'])
    return loader.plugins
```

Then if you run the REPL from the root of the project, you should see something like this.

```python
>>> import core.main
>>> plugins = core.main.load_plugins()
>>> plugins
{'widget': {'terminal': <class 'pluginlib.importer.terminal_object.TerminalObject'>}}
>>> terminal = plugins.widget.terminal()
```

**Comment by enjoysmath** [comment]
What is the REPL?

Thanks.

**Comment by enjoysmath** [comment]
Bad question.  I can google that.  I will look into this later today
or tomorrow.

I'm working on another part of the project at the moment.

Thank you for your help!

-Daniel Donnelly

**Comment by avylove** [comment]
The REPL is the Python console. It's a good way to explore objects outside of a script.
Going to close this since it doesn't seem to be a bug or feature request, but comment here if it's not working for you.
