### ISSUE TITLE
Subdirectory file structure not supported

### ISSUE THREAD

**Issue by s0mnaths** [Rockhopper-Technologies/pluginlib#6]
I am using pluginlib to add the plugin architecture to my application. However, I want to maintain a good folder structure, something like 
```
├── project
│   ├── plugins
│   │   ├── plugin_parents.py
│   │   ├── plugin1.py
│   │   ├── plugin2.py
│   ├── main.py
│   ├── plugins_list.txt
│   ├── requests.py
```

However, it gives me the error saying `plugin1 not found` when I run the program. I tried passing absolute paths too. I'm able to use pluginlib only when all the files are in the same directories.

Can you help me with this?
Thank you.

**Comment by avylove** [comment]
What does your ‘‘PluginLoader‘‘ line look like?
The parents should be part of your main code, not with the plugins.

**Comment by avylove** [comment]
I'm going to assume you are treating project as a package. Your structure should look more like this:

```
├── project
│   ├── plugins
│   │   ├── plugin1.py
│   │   ├── plugin2.py
│   ├── main.py
│   ├── parents.py
```

The the plugins would look something like this:
```python
import json
from project.parents import Parser

class JSON(Parser):

    _alias_ = 'json'

    def parse(self, string):
        return json.loads(string)
```

And you can access them with something like
```python
loader = pluginlib.PluginLoader(modules=['project.plugins'])
plugins = loader.plugins

```

I'm going to go ahead and close this, but if you're still having issues, feel free to comment or reopen.
